"""
Shared fixtures for Feature Validation Tests.

These fixtures are available to all validation tests generated by the
testing-expert agent during pre-commit feature validation.
"""

from collections.abc import Generator
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# =============================================================================
# Environment Fixtures
# =============================================================================


@pytest.fixture
def test_env(monkeypatch) -> None:
    """Set up test environment variables."""
    monkeypatch.setenv("ENV", "test")
    monkeypatch.setenv("DEBUG", "false")
    monkeypatch.setenv("MOCK_EXTERNAL_APIS", "true")


@pytest.fixture
def mock_settings(test_env, tmp_path, monkeypatch):
    """
    Fixture providing mocked Settings for validation tests.

    Uses test environment with temporary paths for isolation.
    """
    from backend.deep_agent.config.settings import Settings

    # MOCK CREDENTIALS - These are fake test values, NOT real API keys.
    # They satisfy Pydantic validation but are never used for actual API calls.
    # Real API keys should ONLY be stored in .env (which is gitignored).
    monkeypatch.setenv("OPENAI_API_KEY", "test-openai-key")  # pragma: allowlist secret
    monkeypatch.setenv("PERPLEXITY_API_KEY", "test-perplexity-key")  # pragma: allowlist secret
    monkeypatch.setenv("LANGSMITH_API_KEY", "lsv2_test_key")  # pragma: allowlist secret
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path}/test.db")

    return Settings()


# =============================================================================
# Mock Fixtures for External Services
# =============================================================================


@pytest.fixture
def mock_openai_client():
    """Mock OpenAI client for validation tests."""
    with patch("langchain_openai.ChatOpenAI") as mock:
        mock_instance = MagicMock()
        mock_instance.invoke = MagicMock(return_value=MagicMock(content="Test response"))
        mock_instance.ainvoke = AsyncMock(return_value=MagicMock(content="Test response"))
        mock.return_value = mock_instance
        yield mock_instance


@pytest.fixture
def mock_perplexity_search():
    """Mock Perplexity web search for validation tests."""
    with patch("backend.deep_agent.tools.web_search.perplexity_search") as mock:
        mock.return_value = {
            "results": [
                {"title": "Test Result", "url": "https://example.com", "snippet": "Test snippet"}
            ]
        }
        yield mock


@pytest.fixture
def mock_langsmith():
    """Mock LangSmith tracing for validation tests."""
    with patch("backend.deep_agent.integrations.langsmith.setup_langsmith") as mock:
        mock.return_value = None
        yield mock


# =============================================================================
# Agent Fixtures
# =============================================================================


@pytest.fixture
def mock_agent():
    """Mock compiled agent graph for validation tests."""
    mock = AsyncMock()
    mock.ainvoke = AsyncMock(
        return_value={"messages": [MagicMock(content="Agent response")], "status": "completed"}
    )
    return mock


@pytest.fixture
def mock_agent_service(mock_settings, mock_agent, mock_langsmith):
    """Mock AgentService for validation tests."""
    from backend.deep_agent.services.agent_service import AgentService

    with patch.object(AgentService, "_create_agent", return_value=mock_agent):
        service = AgentService(settings=mock_settings)
        yield service


# =============================================================================
# API Fixtures
# =============================================================================


@pytest.fixture
def test_client(mock_settings):
    """FastAPI test client for validation tests."""
    from fastapi.testclient import TestClient

    from backend.deep_agent.api.main import app

    # Override settings dependency
    with patch("backend.deep_agent.config.settings.get_settings", return_value=mock_settings):
        with TestClient(app) as client:
            yield client


@pytest.fixture
def async_test_client(mock_settings):
    """Async FastAPI test client for validation tests."""
    from httpx import ASGITransport, AsyncClient

    from backend.deep_agent.api.main import app

    async def get_client():
        with patch("backend.deep_agent.config.settings.get_settings", return_value=mock_settings):
            transport = ASGITransport(app=app)
            async with AsyncClient(transport=transport, base_url="http://test") as client:
                yield client

    return get_client


# =============================================================================
# Data Fixtures
# =============================================================================


@pytest.fixture
def sample_chat_message() -> dict[str, Any]:
    """Sample chat message for validation tests."""
    return {
        "content": "Hello, how can you help me today?",
        "role": "user",
        "metadata": {"source": "validation_test"},
    }


@pytest.fixture
def sample_thread_id() -> str:
    """Sample thread ID for validation tests."""
    return "validation-test-thread-001"


@pytest.fixture
def sample_chat_request(sample_chat_message, sample_thread_id) -> dict[str, Any]:
    """Complete chat request for validation tests."""
    return {
        "messages": [sample_chat_message],
        "thread_id": sample_thread_id,
        "metadata": {"test": True},
    }


# =============================================================================
# Cleanup Fixtures
# =============================================================================


@pytest.fixture(autouse=True)
def cleanup_validation_artifacts(tmp_path) -> Generator[None, None, None]:
    """
    Auto-cleanup fixture for validation test artifacts.

    Runs after each test to clean up any generated files.
    """
    yield

    # Clean up any temporary files created during validation
    validation_dir = Path(__file__).parent
    for pattern in ["*.tmp", "*.pyc", "__pycache__"]:
        for file in validation_dir.glob(pattern):
            if file.is_file():
                file.unlink()
            elif file.is_dir():
                import shutil

                shutil.rmtree(file, ignore_errors=True)


# =============================================================================
# Markers
# =============================================================================


def pytest_configure(config):
    """Register custom markers for validation tests."""
    config.addinivalue_line(
        "markers",
        "validation: marks tests as feature validation tests (generated by testing-expert)",
    )
    config.addinivalue_line("markers", "jira(ticket): marks tests linked to a JIRA ticket")
